"""Geofence DB access — the PostGIS heart of the feature.

DB-only: no business rules, no commits, no HTTP errors. Geometry is stored as
GEOMETRY(POLYGON, 4326); the GIST index on `zone` (see models/geofence.py)
makes ST_Contains fast. Coordinates cross the boundary as [lng, lat] (GeoJSON
/ ST_MakePoint order).
"""
from datetime import datetime

from geoalchemy2 import WKTElement
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.geofence import Geofence


def build_polygon_wkt(coordinates: list[list[float]]) -> str:
    """[[lng,lat], ...] → closed WKT 'POLYGON((lng lat, ...))'."""
    ring = list(coordinates)
    if ring[0] != ring[-1]:
        ring = ring + [ring[0]]  # auto-close
    body = ", ".join(f"{lng} {lat}" for lng, lat in ring)
    return f"POLYGON(({body}))"


class GeofenceRepository:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    # ── Writes (no commit) ────────────────────────────────────────────────
    def create(self, *, name, description, wkt, created_by) -> Geofence:
        """Polygon geofence (ORM insert from WKT)."""
        gf = Geofence(
            name=name,
            description=description,
            zone=WKTElement(wkt, srid=4326),
            shape_type="POLYGON",
            created_by=created_by,
            is_active=True,
        )
        self.db.add(gf)
        return gf

    async def create_circle(
        self,
        *,
        name: str,
        description: str | None,
        center_lat: float,
        center_lng: float,
        radius_meters: float,
        created_by: int | None,
    ) -> int:
        """Circle geofence. The `zone` polygon is a 64-point approximation
        (quad_segs=16 ⇒ 16 segments per quarter × 4 = 64) generated by buffering
        the centre on the GEOGRAPHY type so the radius is in true metres, then
        cast back to GEOMETRY(4326) for storage/spatial queries. Returns the id.
        """
        result = await self.db.execute(
            text(
                """
                INSERT INTO geofences (
                    name, description, zone, shape_type,
                    center_lat, center_lng, radius_meters,
                    created_by, is_active, created_at
                )
                VALUES (
                    :name, :description,
                    ST_Buffer(
                        ST_SetSRID(ST_MakePoint(:lng, :lat), 4326)::geography,
                        :radius, 16
                    )::geometry,
                    'CIRCLE', :lat, :lng, :radius,
                    :created_by, true, now()
                )
                RETURNING id
                """
            ),
            {
                "name": name,
                "description": description,
                "lat": center_lat,
                "lng": center_lng,
                "radius": radius_meters,
                "created_by": created_by,
            },
        )
        return int(result.scalar_one())

    async def get(self, geofence_id: int) -> Geofence | None:
        return await self.db.get(Geofence, geofence_id)

    # ── Geometry reads (GeoJSON for the wire) ─────────────────────────────
    # area is computed on the GEOGRAPHY cast so it comes back in true m²
    # for both polygons and circle approximations.
    _SELECT_COLS = (
        "id, name, description, is_active, created_at, "
        "shape_type, center_lat, center_lng, radius_meters, "
        "ST_AsGeoJSON(zone) AS geojson, "
        "ST_Area(zone::geography) AS area_sq_meters"
    )

    async def list_active(self) -> list[dict]:
        rows = await self.db.execute(
            text(
                f"""
                SELECT {self._SELECT_COLS}
                FROM geofences
                WHERE is_active = true
                ORDER BY name ASC
                """
            )
        )
        return [dict(r) for r in rows.mappings().all()]

    async def get_with_geojson(self, geofence_id: int) -> dict | None:
        row = await self.db.execute(
            text(
                f"""
                SELECT {self._SELECT_COLS}
                FROM geofences WHERE id = :id
                """
            ),
            {"id": geofence_id},
        )
        m = row.mappings().first()
        return dict(m) if m else None

    # ── Point-in-polygon ──────────────────────────────────────────────────
    async def geofences_containing(self, lat: float, lng: float) -> set[int]:
        """IDs of active geofences that contain the point. Raw PostGIS:
        ST_Contains(zone, point) — the GIST index does the heavy lifting."""
        rows = await self.db.execute(
            text(
                """
                SELECT id FROM geofences
                WHERE is_active = true
                  AND ST_Contains(
                        zone,
                        ST_SetSRID(ST_MakePoint(:lng, :lat), 4326)
                      )
                """
            ),
            {"lat": lat, "lng": lng},
        )
        return {r[0] for r in rows.all()}

    # ── Events ────────────────────────────────────────────────────────────
    async def recent_events(self, geofence_id: int, limit: int = 20) -> list[dict]:
        rows = await self.db.execute(
            text(
                """
                SELECT e.id, e.user_id, u.name AS employee_name, e.geofence_id,
                       e.event_type, e.timestamp, e.lat, e.lng
                FROM geofence_events e
                LEFT JOIN users u ON u.id = e.user_id
                WHERE e.geofence_id = :gid
                ORDER BY e.timestamp DESC
                LIMIT :limit
                """
            ),
            {"gid": geofence_id, "limit": limit},
        )
        return [dict(r) for r in rows.mappings().all()]

    # ── Presence: ENTER/EXIT pairing → time inside ───────────────────────
    async def presence(
        self, geofence_id: int, start: datetime, end: datetime
    ) -> list[dict]:
        """Each ENTER paired with the NEXT event per user (LEAD window). If the
        next event is an EXIT we have a closed interval + duration; otherwise
        the person is still inside (exited_at = NULL)."""
        rows = await self.db.execute(
            text(
                """
                WITH ordered AS (
                    SELECT
                        e.user_id,
                        e.event_type,
                        e.timestamp,
                        LEAD(e.timestamp) OVER (
                            PARTITION BY e.user_id ORDER BY e.timestamp
                        ) AS next_ts,
                        LEAD(e.event_type) OVER (
                            PARTITION BY e.user_id ORDER BY e.timestamp
                        ) AS next_type
                    FROM geofence_events e
                    WHERE e.geofence_id = :gid
                      AND e.timestamp >= :start AND e.timestamp < :end
                )
                SELECT
                    o.user_id,
                    u.name AS employee_name,
                    o.timestamp AS entered_at,
                    CASE WHEN o.next_type = 'EXIT' THEN o.next_ts END AS exited_at,
                    CASE WHEN o.next_type = 'EXIT'
                         THEN EXTRACT(EPOCH FROM (o.next_ts - o.timestamp)) / 60.0
                    END AS duration_minutes
                FROM ordered o
                LEFT JOIN users u ON u.id = o.user_id
                WHERE o.event_type = 'ENTER'
                ORDER BY o.user_id, entered_at
                """
            ),
            {"gid": geofence_id, "start": start, "end": end},
        )
        return [dict(r) for r in rows.mappings().all()]

    # ── Per-employee visits for a window (geofences visited + minutes) ────
    async def employee_visits(
        self, user_id: int, start: datetime, end: datetime
    ) -> list[dict]:
        rows = await self.db.execute(
            text(
                """
                WITH ordered AS (
                    SELECT
                        e.geofence_id,
                        e.event_type,
                        e.timestamp,
                        LEAD(e.timestamp) OVER (
                            PARTITION BY e.geofence_id ORDER BY e.timestamp
                        ) AS next_ts,
                        LEAD(e.event_type) OVER (
                            PARTITION BY e.geofence_id ORDER BY e.timestamp
                        ) AS next_type
                    FROM geofence_events e
                    WHERE e.user_id = :uid
                      AND e.timestamp >= :start AND e.timestamp < :end
                )
                SELECT
                    o.geofence_id,
                    g.name AS geofence_name,
                    COUNT(*) FILTER (WHERE o.event_type = 'ENTER') AS visits,
                    COALESCE(SUM(
                        CASE WHEN o.event_type = 'ENTER' AND o.next_type = 'EXIT'
                             THEN EXTRACT(EPOCH FROM (o.next_ts - o.timestamp)) / 60.0
                             ELSE 0 END
                    ), 0) AS total_minutes
                FROM ordered o
                JOIN geofences g ON g.id = o.geofence_id
                GROUP BY o.geofence_id, g.name
                HAVING COUNT(*) FILTER (WHERE o.event_type = 'ENTER') > 0
                ORDER BY total_minutes DESC
                """
            ),
            {"uid": user_id, "start": start, "end": end},
        )
        return [dict(r) for r in rows.mappings().all()]

    # ── Currently inside: last event per user for this zone is ENTER ──────
    async def currently_inside(self, geofence_id: int) -> list[dict]:
        rows = await self.db.execute(
            text(
                """
                SELECT DISTINCT ON (e.user_id)
                    e.user_id, u.name AS employee_name, e.event_type,
                    e.timestamp AS entered_at
                FROM geofence_events e
                LEFT JOIN users u ON u.id = e.user_id
                WHERE e.geofence_id = :gid
                ORDER BY e.user_id, e.timestamp DESC
                """
            ),
            {"gid": geofence_id},
        )
        # Keep only those whose latest event is an ENTER (still inside).
        return [
            dict(r)
            for r in rows.mappings().all()
            if r["event_type"] == "ENTER"
        ]
